version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/vocable-trainer

    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: firebase use vocable-quiz
      - run: firebase deploy --force --non-interactive -m $CIRCLE_SHA1 --token "$FIREBASE_TOKEN"
