name: Push

on:
    - push

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Get node version
              id: node-version
              run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
            - name: Use node ${{ matrix.node }}
              uses: actions/setup-node@v2.3.1

            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      node-
            - run: npm install
            - name: Build
              run: npm run build

            - name: Deploy
              if: github.ref == 'refs/heads/master'
              run: |
                  npm run firebase -- use vocable-quiz
                  npm run firebase -- deploy --force --non-interactive -m $GITHUB_SHA --token $FIREBASE_TOKEN
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
